spring.application.name=sigcilat

spring.datasource.url=jdbc:postgresql://localhost:5432/sigcilat_dev
spring.datasource.username=sigcilat
spring.datasource.password=sigcilat123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City


#Eliminar  posteriormente una ves concluido el desarrollo ya que es lo que se utiliza para hacer el reload de la app 
#al realizar cambios en la alicacion.
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
